//"use strict"
var megatorg = angular.module("megatorg", []);

megatorg.controller('HomeProductsCtrl', function($scope, $http){
	/*$http.get('content/home-products.json').success(function(data){
		$scope.products = data;
		console.log($scope.products);
	});*/
	$scope.products = [
		{
			"id": 1,
			"name": "3D Ultra HD Led телевизор Sony KD-79X9005B",
			"image": "images/content/products/product-1.jpg",
			"rating": 3,
			"reviews": 4,
			"oldprice": 499000,
			"price": 449000,
			"today": true,
			"new": false,
			"bestseller": false,
		},
		{
			"id": 2,
			"name": "Игровая приставка Sony PS4 500GB Black",
			"image": "images/content/products/product-2.jpg",
			"rating": 4,
			"reviews": 13,
			"oldprice": "",
			"price": 27990,
			"today": true,
			"new": false,
			"bestseller": false,
		},
		{
			"id": 3,
			"name": "Овощерезка Moulinex Dj905",
			"image": "images/content/products/product-3.jpg",
			"rating": 1,
			"reviews": 2,
			"oldprice": "",
			"price": 14000,
			"today": true,
			"new": false,
			"bestseller": false,
		},
		{
			"id": 4,
			"name": "Фотоаппарат зеркальный Nikon D3200 kit 18-55VRII Black",
			"image": "images/content/products/product-4.jpg",
			"rating": 4,
			"reviews": 5,
			"oldprice": "",
			"price": 24000,
			"today": true,
			"new": false,
			"bestseller": false,
		},
		{
			"id": 5,
			"name": "Ноутбук Lenovo IdeaPad G5030 (80G000FLRK)",
			"image": "images/content/products/product-5.jpg",
			"rating": 3,
			"reviews": 16,
			"oldprice": 21000,
			"price": 19790,
			"today": true,
			"new": true,
			"bestseller": true,
		},
		{
			"id": 6,
			"name": "Видеокамера экшн GoPro Hero 4 Black Edition Motosport",
			"image": "images/content/products/product-6.jpg",
			"rating": 4,
			"reviews": 117,
			"oldprice": "",
			"price": 29990,
			"today": true,
			"new": true,
			"bestseller": false,
		},
		{
			"id": 7,
			"name": "Автомобильный радар Neoline X-COP 8500",
			"image": "images/content/products/product-7.jpg",
			"rating": 1,
			"reviews": 7,
			"oldprice": "",
			"price": 7600,
			"today": true,
			"new": true,
			"bestseller": true,
		},
		{
			"id": 8,
			"name": "Фотоэпилятор Remington IPL600F",
			"image": "images/content/products/product-8.jpg",
			"rating": 4,
			"reviews": 2,
			"oldprice": "",
			"price": 24990,
			"today": true,
			"new": true,
			"bestseller": false,
		},
		{
			"id": 9,
			"name": "Смартфон Asus Zenfon 4 White",
			"image": "images/content/products/product-9.jpg",
			"rating": 3,
			"reviews": 64,
			"oldprice": 7990,
			"price": 6490,
			"today": false,
			"new": true,
			"bestseller": true,
		},
		{
			"id": 10,
			"name": "Посудомоечная машина (60 см) Siemens SpeedMatic SN26M285RU",
			"image": "images/content/products/product-10.jpg",
			"rating": 4,
			"reviews": 43,
			"oldprice": "",
			"price": 55390,
			"today": false,
			"new": true,
			"bestseller": true,
		},
		{
			"id": 11,
			"name": "Планшет Apple iPad Air 2 Wi-Fi + Cellular 16Gb Black",
			"image": "images/content/products/product-11.jpg",
			"rating": 5,
			"reviews": 237,
			"oldprice": "",
			"price": 32000,
			"today": false,
			"new": false,
			"bestseller": true,
		},
		{
			"id": 12,
			"name": "Кофемашина капсульного типа Nespresso De Longhi EN550.B",
			"image": "images/content/products/product-12.jpg",
			"rating": 4,
			"reviews": 55,
			"oldprice": "",
			"price": 27790,
			"today": false,
			"new": false,
			"bestseller": true,
		},
	];
});
megatorg.controller('CatalogProductsCtrl', function($scope, $http){
	/*$http.get('content/catalog-products.json').success(function(data){
		$scope.products = data;
		//console.log($scope.products);
	});*/
	$scope.orderProp = 'id';
	$scope.products = [
		{
			"id": 1,
			"name": "3D Ultra HD LED телевизор Samsung UE55HU8500T",
			"image": "images/content/products/cataloge-product-1.jpg",
			"rating": 3,
			"reviews": 13,
			"oldprice": 103990,
			"price": 84990,
			"quantity": 1,
		},
		{
			"id": 2,
			"name": "3D Ultra HD LED телевизор Samsung UE65HU9000T",
			"image": "images/content/products/cataloge-product-2.jpg",
			"rating": 4,
			"reviews": 8,
			"oldprice": 240990,
			"price": 223223,
			"quantity": 2,
		},
		{
			"id": 3,
			"name": "3D Ultra HD LED телевизор Philips 50PUS6809",
			"image": "images/content/products/cataloge-product-3.jpg",
			"rating": 1,
			"reviews": 3,
			"oldprice": "",
			"price": 39899,
			"quantity": 3,
		},
		{
			"id": 4,
			"name": "3D Ultra HD LED телевизор Sony KD-49X8505B",
			"image": "images/content/products/cataloge-product-4.jpg",
			"rating": 4,
			"reviews": 11,
			"oldprice": "",
			"price": 73899,
			"quantity": 10,
		},
		{
			"id": 5,
			"name": "LED телевизор Supra STV-LC32T871WL",
			"image": "images/content/products/cataloge-product-5.jpg",
			"rating": 3,
			"reviews": 1,
			"oldprice": 16300,
			"price": 15990,
			"quantity": 0,
		},
		{
			"id": 6,
			"name": "LED телевизор Samsung UE48H5500AK",
			"image": "images/content/products/cataloge-product-6.jpg",
			"rating": 4,
			"reviews": 3,
			"oldprice": "",
			"price": 34990,
			"quantity": 25,
		},
		{
			"id": 7,
			"name": "3D LED телевизор Sony KDL42W828B",
			"image": "images/content/products/cataloge-product-7.jpg",
			"rating": 1,
			"reviews": 33,
			"oldprice": "",
			"price": 29889,
			"quantity": 0,
		},
		{
			"id": 8,
			"name": "3D LED Телевизор LG 42LB653V",
			"image": "images/content/products/cataloge-product-8.jpg",
			"rating": 4,
			"reviews": 45,
			"oldprice": "",
			"price": 29899,
			"quantity": 1,
		},
		{
			"id": 9,
			"name": "LED телевизор LG 55LF630V",
			"image": "images/content/products/cataloge-product-9.jpg",
			"rating": 3,
			"reviews": 1,
			"oldprice": 75000,
			"price": 68899,
			"quantity": 5,
		},
		{
			"id": 10,
			"name": "LED телевизор Samsung UE55H6800AU",
			"image": "images/content/products/cataloge-product-10.jpg",
			"rating": 4,
			"reviews": 4,
			"oldprice": "",
			"price": 59899,
			"quantity": 0,
		},
		{
			"id": 11,
			"name": "Ultra LED телевизор Samsung UE48J6330AU",
			"image": "images/content/products/cataloge-product-11.jpg",
			"rating": 1,
			"reviews": 1,
			"oldprice": "",
			"price": 50899,
			"quantity": 10,
		},
		{
			"id": 12,
			"name": "Ultra LED Телевизор Samsung UE46H7000AT",
			"image": "images/content/products/cataloge-product-12.jpg",
			"rating": 4,
			"reviews": 9,
			"oldprice": "",
			"price": 49899,
			"quantity": 1,
		},
		{
			"id": 13,
			"name": "Ultra HD Led телевизор Samsung UE40J5510AU",
			"image": "images/content/products/cataloge-product-13.jpg",
			"rating": 3,
			"reviews": 0,
			"oldprice": 35000,
			"price": 33899,
			"quantity": 3,
		},
		{
			"id": 14,
			"name": "Ultra LED телевизор Sony KDL48R553C",
			"image": "images/content/products/cataloge-product-14.jpg",
			"rating": 4,
			"reviews": 2,
			"oldprice": "",
			"price": 46899,
			"quantity": 6,
		},
		{
			"id": 15,
			"name": "3D Ultra HD LED телевизор Samsung UE85HU8500",
			"image": "images/content/products/cataloge-product-15.jpg",
			"rating": 1,
			"reviews": 1,
			"oldprice": "",
			"price": 494899,
			"quantity": 15,
		},
		{
			"id": 16,
			"name": "LED телевизор LG 32LB582V",
			"image": "images/content/products/cataloge-product-16.jpg",
			"rating": 4,
			"reviews": 9,
			"oldprice": "",
			"price": 20899,
			"quantity": 0,
		},
	];
});